### ISSUE TITLE
Segfault when trying to launch the last build with hardfork

### ISSUE THREAD

**Issue by Cryptoslave** [Anoncoin/oldrepo-backup#95]
After building https://github.com/Anoncoin/anoncoin/commit/221c6b6b853a6a9fb37365e553ac02f794be7739 without any trouble, both for windows or for linux; on running the anoncoin-qtc segfault on linux and crash on windows.

**Comment by Cryptoslave** [comment]
yo@yo-VirtualBox ~/anoncoin/src/qt $ ulimit -c unlimited
yo@yo-VirtualBox ~/anoncoin/src/qt $ ./anoncoin-qtc
Segmentation fault (core dumped)
yo@yo-VirtualBox ~/anoncoin/src/qt $ gdb anoncoin-qtc core
GNU gdb (Ubuntu 7.7-0ubuntu3.1) 7.7
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
http://www.gnu.org/software/gdb/bugs/.
Find the GDB manual and other documentation resources online at:
http://www.gnu.org/software/gdb/documentation/.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from anoncoin-qtc...(no debugging symbols found)...done.
[New LWP 21457]
[New LWP 21458]
[New LWP 21462]
[New LWP 21451]
[New LWP 21463]
[New LWP 21459]
[New LWP 21460]
[New LWP 21450]
[New LWP 21452]
[New LWP 21461]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./anoncoin-qtc'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f14539cc2aa in CheckBlockHeader(CBlockHeader const&, CValidationState&, bool) ()
warning: File "/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19-gdb.py" auto-loading has been declined by your`auto-load safe-path' set to "$debugdir:$datadir/auto-load".
To enable execution of this file add
        add-auto-load-safe-path /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.19-gdb.py
line to your configuration file "/home/yo/.gdbinit".
To completely disable this security protection add
---Type <return> to continue, or q <return> to quit---
        set auto-load safe-path /
line to your configuration file "/home/yo/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
        info "(gdb)Auto-loading safe path"
(gdb) where
#0  0x00007f14539cc2aa in CheckBlockHeader(CBlockHeader const&, CValidationState&, bool) ()
#1  0x00007f14539d6464 in CheckBlock(CBlock const&, CValidationState&, bool, bool) ()
#2  0x00007f14539e2ca9 in ConnectBlock(CBlock const&, CValidationState&, CBlockIndex_, CCoinsViewCache&, bool) ()
#3  0x00007f14539e7553 in ActivateBestChain(CValidationState&, CBlock_) ()
#4  0x00007f14539f044f in InitBlockInde) ()
#5  0x00007f14539a9a13 in AppInit2(boost::thread_group&) ()
#6  0x00007f14538c798f in AnoncoinCoin::initialize() ()
#7  0x00007f14538c8d58 in AnoncoinCoin::qt_metacall(QMetaObject::Call, int, void*_) ()
#8  0x00007f1452025c1e in QObject::event(QEvent_) ()
   from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#9  0x00007f1452b09e2c in QApplicationPrivate::notify_helper(QObject_, QEvent_)
    () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#10 0x00007f1452b104a0 in QApplication::notify(QObject_, QEvent_) ()
   from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#11 0x00007f145200d4dd in QCoreApplication::notifyInternal(QObject_, QEvent_)
    () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#12 0x00007f1452010b3d in QCoreApplicationPrivate::sendPostedEvents(QObject_, int, QThreadData_) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#13 0x00007f145203af83 in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
---Type <return> to continue, or q <return> to quit---
#14 0x00007f1450558e04 in g_main_context_dispatch ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#15 0x00007f1450559048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007f14505590ec in g_main_context_iteration ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#17 0x00007f145203a7a1 in QEventDispatcherGlib:rocessEvents(QFlagsQEventLoop:rocessEventsFlag) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#18 0x00007f145200c0af in QEventLoop:rocessEvents(QFlagsQEventLoop:rocessEventsFlag) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#19 0x00007f145200c3a5 in QEventLoop::exec(QFlagsQEventLoop:rocessEventsFlag) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#20 0x00007f1451f08c5f in QThread::exec() ()
   from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#21 0x00007f1451f0b32f in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#22 0x00007f1451a70182 in start_thread ()
   from /lib/x86_64-linux-gnu/libpthread.so.0
#23 0x00007f1450d6afbd in clone () from /lib/x86_64-linux-gnu/libc.so.6
(gdb)

**Comment by Cryptoslave** [comment]
Solved https://github.com/Anoncoin/anoncoin/commit/c406063eb69ff9ddf62bb87c85a3513cce7d6789
